-- SOLUÇÃO 1: SISTEMA DE PERFIS MÚLTIPLOS
-- =====================================================

-- Nova tabela para relacionamento muitos-para-muitos
CREATE TABLE IF NOT EXISTS "usuario_perfil" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "usuario_id" int NOT NULL,
    "perfil_id" int NOT NULL,
    "ativo" boolean NOT NULL DEFAULT TRUE,
    "concedido_por_usuario_id" int,
    "data_concessao" timestamp DEFAULT (now()),
    "observacoes" text,
    FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id"),
    FOREIGN KEY ("perfil_id") REFERENCES "perfil" ("id"),
    FOREIGN KEY ("concedido_por_usuario_id") REFERENCES "usuario" ("id"),
    UNIQUE("usuario_id", "perfil_id")
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_usuario_perfil_usuario_id ON usuario_perfil(usuario_id) WHERE ativo = TRUE;
CREATE INDEX IF NOT EXISTS idx_usuario_perfil_perfil_id ON usuario_perfil(perfil_id) WHERE ativo = TRUE;

-- View para facilitar consultas
CREATE OR REPLACE VIEW v_usuario_perfis AS
SELECT 
    u.id as usuario_id,
    u.nome as usuario_nome,
    u.email,
    array_agg(p.nome ORDER BY p.nome) as perfis,
    array_agg(p.id ORDER BY p.nome) as perfil_ids,
    string_agg(p.nome, ', ' ORDER BY p.nome) as perfis_texto
FROM usuario u
LEFT JOIN usuario_perfil up ON u.id = up.usuario_id AND up.ativo = TRUE
LEFT JOIN perfil p ON up.perfil_id = p.id AND p.ativo = TRUE
WHERE u.ativo = TRUE
GROUP BY u.id, u.nome, u.email;

-- Migração dos dados existentes
INSERT INTO usuario_perfil (usuario_id, perfil_id, concedido_por_usuario_id, observacoes)
SELECT 
    u.id, 
    u.perfil_id, 
    1, -- Assumindo que admin tem ID 1
    'Migração automática do sistema anterior'
FROM usuario u 
WHERE u.ativo = TRUE 
AND u.perfil_id IS NOT NULL;

-- Comentários de documentação
COMMENT ON TABLE usuario_perfil IS 'Relacionamento N:N entre usuários e perfis - permite múltiplos perfis por usuário';
COMMENT ON COLUMN usuario_perfil.concedido_por_usuario_id IS 'Administrador que concedeu este perfil ao usuário';
COMMENT ON COLUMN usuario_perfil.observacoes IS 'Justificativa para concessão do perfil adicional';